### ISSUE TITLE
asciify-paths

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#11]
http://beets.readthedocs.org/en/latest/reference/config.html#asciify-paths

another useful feature?

**Comment by Schweinepriester** [comment]
yes but i think we dont need it, see allowed characters:

| FS | Allowed characters in filenames |
| --- | --- |
| [NTFS](http://en.wikipedia.org/wiki/NTFS) | In POSIX namespace, any UTF-16 code unit (case-sensitive) except U+0000 (NUL) and / (slash). In Win32 namespace, any UTF-16 code unit (case-insensitive) except U+0000 (NUL) / (slash) \ (backslash) : (colon) \* (asterisk) ? (Question mark) " (quote) < (less than) > (greater than) and | (pipe) |
| [HFS Plus](http://en.wikipedia.org/wiki/HFS_Plus) | Unicode, any character, including NUL. OS APIs may limit some characters for legacy reasons |

and because those characters are catched by http://beets.readthedocs.org/en/latest/reference/config.html?highlight=trailing#replace

i'd link to change 

``` yaml
replace:
    '^\.': _
```

to 

``` yaml
replace:
    '^\.': 
```

though, to remove any trailing dots and not replace them by `_`

on the other hand, ascii paths would be probalby better searchable in the file managers

**Comment by zabelhaft** [comment]
i added the default values in the `config.yaml`

feel free to change the trailing dot behaviour

#ascii: other pros/cons

**Comment by Schweinepriester** [comment]
done (damn, missed to mention the issue in the commit)

#ascii:

i dont know, right now we even have cyrillic folder/file names...

since we usually use itunes (or other programs) which handle stuff like this (e.g. map `e` to `é`) i think we should have the most accurate folder/file structure possible... i guess?

**Comment by zabelhaft** [comment]
trust in unicode! #close
