### ISSUE TITLE
features for 0.0.2

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#4]
- [x]  lyric autoimport (Lyric Plugin)
- [x] Guess metadata for untagged tracks from their filenames (FromFilename Plugin)
- [ ] tag files from acoustic fingerprint (Chromaprint/Acoustid Plugin)
- [x] merge configs
- [ ] test albums without album artist (compilations, soundtracks)
- [x] add ftintitle plugin

**Comment by Schweinepriester** [comment]
just finished a basic implementation of the lyrics plugin

`force: yes` because i think we should always try to fetch some, assuming they are the same or better, [because](https://beets.readthedocs.org/en/v1.3.13/plugins/lyrics.html#configuration)

> fallback: By default, the file will be left unchanged when no lyrics are found.

implying if there are some, but the internet doesnt knows them, keep the existing lyrics

---

further improvement could be: using a `google_API_key` to activate https://cse.google.com/cse/publicurl?cx=009217259823014548361:lndtuqkycfu which makes among others the lyrics from http://metrolyrics.com available.

which i assume is important, since one of my favorite bands post their lyrics there on their own, e.g. http://www.metrolyrics.com/1000mods-lyrics.html

**Comment by Schweinepriester** [comment]
- [ ] test albums without album artist (compilations, soundtracks)
- [ ] tag files from acoustic fingerprint (Chromaprint/Acoustid Plugin)

postponed to 0.1.0, will create issues
