### ISSUE TITLE
plugin fetchart

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#9]
http://beets.readthedocs.org/en/latest/plugins/fetchart.html
activate `remote_priority:` ?

i do usually dump local pictures right away, although fetchart would be reasonably faster when using local images.

on the other hand, why not use local cover art that reflects out set standards in width and ratio?

**Comment by Schweinepriester** [comment]
apparently i had set this: https://github.com/Schweinepriester/swp-import/blob/master/config.yaml

i think we should set this to `yes`, because as we now local pictures are often low res and crappy, also `sources` defaults to `coverart itunes albumart amazon google wikipedia` which i would have set in this order, too

for the future though:

the question remaining is how this relates to #5. or: how good are the images from coverart? recently i had a lot of (free) albums from bandcamp, in which case the best image was on bandcamp itself, but several times not on e.g. google

another way to ask it: how good are the images from coverart from unpopular/new bands?

**Comment by zabelhaft** [comment]
so `remote_priority: yes` prefers online sources in the defined ordner and searches for local images if no suitable online source is obtained??

we should change it to `yes`

**Comment by Schweinepriester** [comment]
correct, from http://beets.readthedocs.org/en/latest/plugins/fetchart.html

> remote_priority: Query remote sources every time and use local image only as fallback.

i agree as above ;)
